### ISSUE TITLE
Empire Doesnt create external listeners

### ISSUE THREAD

**Issue by PandoraSec** [adaptivethreat/Empire#348] opened 2016-10-04 06:03 UTC
## Empire Version
1.6.0 beta and master

## OS Information (Linux flavor, Python version)
Kali linux python 2.7

## Screenshot of error, embedded text output, or Pastebin link to the error
[!] Error starting listener on port 1500: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 1500, port likely already in use.

## Any additional information
when i try to set a external listener i have an error, it says that the port its already in use,i have the ports open but only happen when i try to set it with the external ip, if i try to set internal, it works.

**Comment by atkinsj** [comment] 2016-10-04 06:51
This is discussed in #327 and is resolved in the 2.0_beta branch, I'm not sure if there was a conclusion for 1.6.

**Comment by skuta** [comment] 2016-10-04 17:10
Use DNS name instead. it'll work.

**Comment by rvrsh3ll** [comment] 2016-10-05 01:15
Hello, I'm unable to reproduce. The current version will resort to listening on 0.0.0.0 if it can't bind to an external IP. Have you done a git pull for the latest version?

**Closed** 2016-10-05 20:41 UTC
