### ISSUE TITLE
Keylogging/Screenshots not working on Server 2008 R2

### ISSUE THREAD

**Issue by leesoh** [adaptivethreat/Empire#187] opened 2016-04-14 18:58 UTC
## Empire Version
1.5.0

## OS Information (Linux flavor, Python version)
Linux kali 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux
Python 2.7.11+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Agent created on fresh Server 2008 R2 DC using lateral_movement/invoke_wmi. Neither keylogging nor screenshots work. Screenshot results in the error below.

## Screenshot of error, embedded text output, or Pastebin link to the error
utput saved to ./downloads/SBPELKREUVLLSKXY/error running c/2016-04-14_12-43-47.omman

**Comment by mubix** [comment] 2016-04-14 19:06
I've run into the same issue on a number of occasions.

**Comment by enigma0x3** [comment] 2016-04-15 12:58
Interesting, let me get a 2008r2 box up and I will test this.

Thanks!

**Comment by leesoh** [comment] 2016-04-15 14:50
No problem - I'll be poking around in the lab today so if you need any more information.

**Comment by HarmJ0y** [comment] 2016-04-21 10:15
I've seen this before a few times but am not sure of the exact issue, we'll try to chase it down.

**Comment by enigma0x3** [comment] 2016-04-25 12:23
I am still working on getting my server 2008r2 box updated (curse windows updates!). I should have this tested today.

**Comment by enigma0x3** [comment] 2016-04-25 13:01
If you have a 2008r2 box you can get to, does someone mind running this and pasting the output?

```
Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -recurse |
Get-ItemProperty -name Version,Release -EA 0 |
Where { $_.PSChildName -match '^(?!S)\p{L}'} |
Select PSChildName, Version, Release, @{
  name="Product"
  expression={
      switch($_.Release) {
        378389 { [Version]"4.5" }
        378675 { [Version]"4.5.1" }
        378758 { [Version]"4.5.1" }
        379893 { [Version]"4.5.2" }
        393295 { [Version]"4.6" }
        393297 { [Version]"4.6" }
        394254 { [Version]"4.6.1" }
        394271 { [Version]"4.6.1" }
      }
    }
}
```

**Comment by leesoh** [comment] 2016-04-25 13:57
Sure thing. I'm out of town right now but will give this a go Tuesday or
Wednesday.

**Comment by leesoh** [comment] 2016-04-26 18:32
PSChildName                                       Version        Release Product
-----------                                                -------           -------     -------
v2.0.50727                                            2.0.50727.5420
v3.0                                                       3.0.30729.5420
Windows Communication Foundation   3.0.4506.5420
Windows Presentation Foundation        3.0.6920.5011
v3.5                                                       3.5.30729.5420

**Comment by enigma0x3** [comment] 2016-04-27 12:00
From what I have seen on ops, the ".omman" extension typically means the box doesn't have anyone interactively logged on (thus no way to grab screenshots/keystrokes). When getting this, are you able to verify that there is an interactive session (RDP, direct login) on the box?

**Comment by leesoh** [comment] 2016-04-27 14:18
Yes there was as I was testing the key logging. I'll try again later this
morning to be sure.

**Comment by enigma0x3** [comment] 2016-04-28 11:57
Interesting, I setup a 2008r2 server with those exact .NET versions and was unable to reproduce. Any security products or anything like that installed? I'm just grasping for straws at this point.

**Comment by leesoh** [comment] 2016-04-28 12:44
It's a fresh VM installed as a DC. A colleague had the same problem; I've
asked him to verify as well.

**Comment by leesoh** [comment] 2016-04-30 15:37
Just tested this again (same victim, same attacking machine/Empire version) and everything is working fine. I'll have more of an opportunity to test this in the coming weeks and will see if I can replicate.

**Comment by enigma0x3** [comment] 2016-05-09 13:01
Cool, let me know if you are able to replicate. I have been unable to replicate this on a fully updated 2008r2 box.

Thanks!

**Comment by leesoh** [comment] 2016-05-09 14:17
Will do!

**Comment by enigma0x3** [comment] 2016-06-04 00:55
Hey @leesoh,
I'm going to go ahead and close this. If you are able to replicate again, let me know and we can go from there.

Thanks!

**Comment by leesoh** [comment] 2016-06-04 01:49
I definitely will. Should be playing around with it more in the coming
weeks. Cheers and thanks for all the work you've done on this excellent
project!

**Comment by leesoh** [comment] 2016-06-21 03:12
This may be asking for a giant troubleshooting headache. If that's the case, tell me to take a hike. I have this issue en masse across two different kali machines (latest version of Empire, rolling) created by two different people and about 50 different endpoints. Is there somewhere in Empire I can go to get more information about what the agent is doing? Would love to get to the bottom of this.

**Comment by leesoh** [comment] 2016-06-24 00:47
A bit more info - my colleague said that if he copied the ps1 over and ran it, it was successful.

**Comment by leesoh** [comment] 2016-07-13 12:40
@enigma0x3 Just realized you may not be checking old closed tickets for updates.

**Comment by HarmJ0y** [comment] 2016-07-15 21:53
We definitely know it's an issue but we can't get an exact reproducible set of steps. We'll leave this open for additional information/comments as we try to work through it.

**Comment by leesoh** [comment] 2016-07-15 21:55
I'm happy to help any way that I can. Will hopefully have some time to experiment more with this in the coming weeks. Will post any new information here.

**Comment by enigma0x3** [comment] 2016-07-17 02:09
Sounds good! I'll re-stand up a 2008 box and re-test this to make sure I didn't miss something.

**Comment by leesoh** [comment] 2016-07-17 02:11
I just tested it on a couple of lab machines at my home, no problem. Building a new domain from scratch over the next week so they'll all be fresh as well.

**Comment by leesoh** [comment] 2016-07-17 17:09
@enigma0x3 Replicated. Here's what I did:

1. Built a brand new box for Empire (Linux namehere 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux)
2. Built a new 2k8r2 template using fresh MSDN media
3. Set up a http listener
4. Tested a launcher but couldn't get an Empire agent working on the standalone server
5. DCPROMO on server, reboot, logon as domain admin
6. Able to get an agent going with both Invoke-WMI from a non-domain-joined Win7 box and with the launcher
7. Interact with agent, usemodule collection/screenshot, execute
`Output saved to ./downloads/MGK242U4NBCL3NLD/error running c/2016-07-17_11-01-11.omman`

Output of the previously requested GCI:

PSChildName | Version | Release | Product
---|---|---|---
v2.0.50727|2.0.50727.5420||
v3.0|3.0.30729.5420||
Windows Communication Foundation|3.0.4506.5420||
Windows Presentation Foundation|3.0.6920.5011||
v3.5|3.5.30729.5420||

**Comment by leesoh** [comment] 2016-07-19 00:56
Just to add to the strangeness, I realized that I'd forgotten to sysprep my 2k8r2 template before deploying. Turfed the old VM, sysprepped, recreated server and DC, then fired up a launcher to the same Empire box/listener. Screenshot and keylogger works just fine.

**Comment by enigma0x3** [comment] 2016-08-07 05:56
So everything appears to be working now?

**Comment by leesoh** [comment] 2016-08-08 02:24
On that particular machine, yes, but generally no. I was just pointing out that an almost identical machine with the same Empire listener/stager had different results.

**Comment by enigma0x3** [comment] 2016-09-10 20:57
Do you have any ideas as to what could possibly be causing intermittent screenshot/keylogging results? I have stood up 6-7 separate 2k8r2 boxes and am unable to get the issue to occur.

**Comment by leesoh** [comment] 2016-09-10 21:21
I have no idea. Especially since it doesn't appear to be tied to a specific version of Windows or even a specific instance of a VM. In my testing, I used the same base image and deployed two VMs from it. One worked, the other didn't. Antivirus wasn't in the mix, nor was any additional software. Just a fresh out of the box server. Are you building your test VMs from an image, or from media? Is this the first module you run? My testing has been focused on this single issue, so it's build from media > launch stager using launcher > test functionality.

On a recent engagement, a colleague and I had two Kali instances and ~90 endpoints compromised. These were production machines with your usual endpoint stuff on them (antivirus, etc.) and none of the ones we attempted worked. Meterpreter worked fine on the same machines.

**Comment by leesoh** [comment] 2016-09-10 21:22
Perhaps @mubix can share his experiences?

**Comment by leesoh** [comment] 2016-09-15 14:20
A comment from another issue got me thinking. @enigma0x3 How are you testing this? On VMs I'm assuming? Are there any components in the module or the agent/server communication that are sensitive to time skew? I've had problems with this VM to VM (same hypervisor) and VM to physical (completely different time sources).

Bit of a hail mary, but thought it worth mentioning.

**Comment by rvrsh3ll** [comment] 2016-10-18 13:40
Screenshots need to be taken in the context of the user you want to screenshot.

**Closed by rvrsh3ll** 2016-10-18 13:40 UTC
