### ISSUE TITLE
Bug in listeners - list command

### ISSUE THREAD

**Issue by CaledoniaProject** [adaptivethreat/Empire#324] opened 2016-09-20 16:10 UTC
## Empire Version
master, lastest

## OS Information (Linux flavor, Python version)
Ubuntu 160.4

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

First run ./setup/reset.sh
Then in empire,
>listeners
>set Host 172.16.1.100
>list

The host field is 172.16.1.100, but actually 172.16.1.100:8080

Was it a bug?

**Comment by leesoh** [comment] 2016-09-20 17:50
This looks like a duplicate of #264, which was closed but I think needs to be reopened.

**Comment by CaledoniaProject** [comment] 2016-09-21 02:03
Bug 2

If I set Host to `ip:port`, the result would be `ip:port:8080`

**Comment by rvrsh3ll** [comment] 2016-09-29 21:15
I've picked this up for analysis. Will check back if I have questions. Thanks for the info!

**Comment by rvrsh3ll** [comment] 2016-09-29 22:06
The reset defaults to port 80. Otherwise, I'm not sure what the issue is here. Please provide more info if needed. Thanks!

**Comment by rvrsh3ll** [comment] 2016-09-30 15:27
I believe I have resolved this issue. Please test and let me know.

**Comment by leesoh** [comment] 2016-09-30 16:01
You've resolved both that issue and the one I mentioned in #264.

**Comment by leesoh** [comment] 2016-10-05 01:54
I think some logic needs to be added to the Host/CertPath/Port sets when creating listeners. As it stands now, the only order you can set these three values and have the listener work is:
```
set CertPath <blah>
set Host <blah>
set Port <blah>
```
This occurs only when you're setting the host by IP, not https://<blah> or http://<blah>

**Closed** 2016-10-05 20:40 UTC

**Comment by HarmJ0y** [comment] 2016-10-06 21:10
This got an additional fix today- https://github.com/adaptivethreat/Empire/commit/3ddfe7786fc84ce0fc27aed5db0a318cb0904455 . Should cover even more bases, let me know if there's still an issue.
